### ISSUE TITLE
Tags not colored properly

### ISSUE THREAD

**Issue by b3u** [insanum/obsidian_nord#1]
Tags are colored grey in the default dark theme. In Nord, the hashtag sign is different from the rest of the tag.
(See Screenshot :point_down:)
![Screenshots of Default & Nord themes](https://user-images.githubusercontent.com/39805353/83584734-003bbd00-a516-11ea-9aec-b82e56aca16e.png)

Suggestion: The tag should all be one color.

**Comment by insanum** [comment]
Ah yes. Thanks for the report. This has been fixed and I also tweaked the colors used for backlinks as well. Looks much better.
