### ISSUE TITLE
how to change the margin?

### ISSUE THREAD

**Issue by OrdinaryYZH** [insanum/obsidian_nord#10]
Because the code display is incomplete，but I don't know how to change in obsidian.css :(

![image](https://user-images.githubusercontent.com/10287222/99222195-00f2b200-281d-11eb-84fe-e6b113c002dc.png)

Another question, how to change the preview like editview that the code wrap auto？

![image](https://user-images.githubusercontent.com/10287222/99222432-85ddcb80-281d-11eb-8cae-944157fb011c.png)

thank you very much~

**Comment by insanum** [comment]
What your asking has nothing to do with the Nord theme itself. There are settings in Obsidian to do what you want.
See `Options->Editor->Readable Line Length` and `Options->Editor->Line Wrap`.
