### ISSUE TITLE
Fonts (Hack Nerd Font/Source Code Pro) not activated

### ISSUE THREAD

**Issue by ituri** [insanum/obsidian_nord#11]
Hi,

I love the colours of _obsidian_nord_ but unfortunately the fonts don't seem to work as they should. I had a look at the CSS and found that the theme is supposed to use `Hack Nerd Font` and/or 'Source Code Pro'. 
I am running Mac OS Big Sur and have installed both fonts via homebrew. When I try to use them in another app like TextEdit, they work flawlessly. Therefore I suppose that they are installed correctly. 
However, they don't get applied in Obsidian. When I'm in edit mode, it falls back to the default font (Arial?) but doesn't use either of the two fonts.
Is there anything else I can do to make the theme work?

Thanks
ituri

**Comment by ituri** [comment]
I'm not fluent in CSS at all but I think I've found a solution. Right now, the font-family for the editor is defined with the selecor `.cm-formatting`. However, it seems that in recent builds of Obsidian the font-family for the editor needs to be defined with the `.cm-s-obsidian` selector, which is not defined in the current version of your theme.

I will do a pull request shortly.

**Comment by sanpedrodeatacama** [comment]
@ituri thanks for this. I love Nord but am trying to get the edit mode font (Hack Nerd) to instead be like the preview mode font (Arial, Helvetica, or Sans Serif?), but I have no idea what I'm doing with css snippets. Do you know what my css file should say to get rid of the Hack Nerd Font and have edit and preview both have that same standard font like preview mode?

In the font issue update I see 

 ```
--default-font: -apple-system, BlinkMacSystemFont, Segoe UI,
    Helvetica, Arial, sans-serif, Apple Color Emoji,
    Segoe UI Emoji;
```

 ```
 --editor-font: 'Hack Nerd Font', 'Source Code Pro',
    ui-monospace, SFMono-Regular, SF Mono, Menlo,
    Consolas, Liberation Mono, monospace;
```

But I haven't been able to change the editor font to anything else successfully yet. Thanks for any help here.

**Comment by insanum** [comment]
If I understand correctly, you want the editor and preview to use the same non-monospace font. Try this CSS snippet:

```css
.markdown-source-view {
  font-family: var(--default-font);
}
```

**Comment by sanpedrodeatacama** [comment]
@insanum wow this worked great, thanks! It looks a little different font from whatever the Preview font was, but still looks good. And thanks for all of your work on the theme. I just updated it today and really appreciate the different highlight colors when searching in the sidebar and within the note. The whole color scheme is so well done.
