### ISSUE TITLE
When the font is bold, the display is not obvious

### ISSUE THREAD

**Issue by drrrMikado** [insanum/obsidian_nord#13]
Thanks for giving us a great theme.
When the font is bold, the display is not obvious.
Example:
![image](https://user-images.githubusercontent.com/11224565/104583563-3cceba00-569c-11eb-9e16-b72381386ef0.png)
"内核线程" and "用户线程" are bolded.

Can increase the contrast of bold font?

**Comment by insanum** [comment]
The font-weight for bold is set at 600. It's the same in many other themes and they all suffer from bold not popping like you think it would. I'm not going to change the default in the theme but you can easily override the bold weight with the following Obsidian CSS snippet (which would override every theme you use):

```css
strong
{
    font-weight: 800 !important;
}
```
