### ISSUE TITLE
CSS for Styling Tags

### ISSUE THREAD

**Issue by shawnduggan** [insanum/obsidian_nord#16]
Love this theme - thank you.

Can you add styling to tags for random pill colours, or share a CSS snippet that can be used to style them as such?

**Comment by filmgal** [comment]
I would also love this. I wouldn't mind pills, but I'm fine with just changing the colour of tags. I've been able to modify quite a few things, but have never been able to change the tag colour.

**Comment by insanum** [comment]
Glad you like Nord! :-)
I've added subtle pills around tags and tweaked the colors.
