### ISSUE TITLE
Better Light theme 

### ISSUE THREAD

**Issue by bhomiatanay19** [insanum/obsidian_nord#18]
Hello I am using the Obsidian Nord theme but as I have themed my PC with obsidian light I wanted to use the Nord light them but it is not what I want 
![Screenshot from 2021-05-31 17-02-40](https://user-images.githubusercontent.com/84649072/120187149-0f8d3d80-c232-11eb-87e9-5ec8cb277301.png)
The Headings are a bit off they are too fade and dont even stand out sometimes can you increase the saturation of the Heading it would be very helpful

**Comment by insanum** [comment]
I think Nord is hard to define on a light background. The colors are subdued so contrast is minimal whereas it pops much cleaner on a dark background.

Could you try tweaking the colors yourself and submit a pull request?

**Comment by insanum** [comment]
Theme has been rewritten for Obsidian 0.16.
