### ISSUE TITLE
Highlight color of search

### ISSUE THREAD

**Issue by Superfeuchter** [insanum/obsidian_nord#21]
I love your theme very much, but I have a big problem with searches in a note.
Especially if text is highlighted, it is hard to distinguish between search results and the rest of the text.
I use the dark theme.
I wish, that there could be another color for search-results. This would be very useful.

![image](https://user-images.githubusercontent.com/83219956/136697107-873556b3-b7e1-4648-aff9-7a5fca9af599.png)
 
The second thing is the mark of the spaced-repetition plugin. I think it could be in a lighter color, smaller or both.

**Comment by insanum** [comment]
Yes it is hard to see. I've tweaked the search highlight colors to be more noticeable.

**Comment by Superfeuchter** [comment]
COOOL! Thank's a lot for this update! Nice Color!
Now it's much easier to work with long documents.

**Comment by Superfeuchter** [comment]
Well, after the update, I cannot change fontsize per mousewheel anymore, although it is activated.
It works with default theme, but not with obsidian nord.

**Comment by Superfeuchter** [comment]
I tried it a few times. Changed Themes. Tried other programs.
Scrolling with ctrl+mousewheel works in my browser etc., and with another obsidian-themes, but when I come back to obsidian nord nothing happens. I use Windows 10.
I'm sorry.

**Comment by insanum** [comment]
No problem. Maybe file a new issue on this for tracking?

Btw, are you trying to change the font size in the preview window or the editor?
