### ISSUE TITLE
Double Image preview with codemirror and oz image in editor

### ISSUE THREAD

**Issue by javiavid** [insanum/obsidian_nord#22]
I'm trying several themes and I like yours, but if I have activated codemirror and oz image in editor the images appear 2 times.

I only get this on your theme.

I could deactivate one of the 2 plugins, but codemirror has no excalidraw preview.

**Comment by insanum** [comment]
This is fixed indirectly. The img style no longer centers images and they're now left aligned (Obsidian default). For whatever reason, the centering is what was causing this problem.
