### ISSUE TITLE
CTRL+Mousewheel doesn't change fontsize in Editor-Mode

### ISSUE THREAD

**Issue by Superfeuchter** [insanum/obsidian_nord#23]
After the recent update the fontsize doesn't change, although it is activated in preferences.
It works in preview-mode, but not in editor mode.
And it works in other programs like Google Chrome, Word etc.
I made a few tests:
I used the obsidian blank theme →   everything's fine.
I used another theme →   works
I deactivated any plugins (turned on safe mode) →   no changes

My system: Windows 10

Any idea?

**Comment by Superfeuchter** [comment]
Experiment:
I found an old version of the theme in a backup-folder and replaced the new file in themes-folder of Obsidian.
Voilá!
Now it works. Filesize changes again.
... but with the disadvantage of the "old" color in search ...

**Comment by insanum** [comment]
fixed

**Comment by Superfeuchter** [comment]
Oh yes!
I just updated the theme, and now I'm happy!
Thanks!
