### ISSUE TITLE
Tags on Light Theme are invisible

### ISSUE THREAD

**Issue by nwehrle** [insanum/obsidian_nord#25]
Current: Tags on Light Theme are invisible, because fgColor is white as well as the bgColor.
Expected: Tags are visible, maybe dark greenish ..

**Comment by insanum** [comment]
When was the last time you updated the Nord theme in Obsidian? The tags in light mode look ok to me.

![Screen Shot 2021-11-22 at 2 12 15 PM](https://user-images.githubusercontent.com/515747/142942909-25cf005b-8ffb-4fca-aabf-f0ef31188577.png)

**Comment by nwehrle** [comment]
Hi, I updated yesterday and right now. I have no custom CSS snippets.

<img width="417" alt="Screenshot 2021-11-23 at 06 30 42" src="https://user-images.githubusercontent.com/832234/142975580-bc31e019-def9-4e3d-a3f3-0a824e972d3e.png">

vs

<img width="440" alt="Screenshot 2021-11-23 at 06 30 59" src="https://user-images.githubusercontent.com/832234/142975596-f67f1c70-87db-4df1-a74d-74f4d37da540.png">

**Comment by nwehrle** [comment]
Preview Mode is fin
<img width="393" alt="Screenshot 2021-11-23 at 06 35 27" src="https://user-images.githubusercontent.com/832234/142975867-e77736c1-3d4e-4830-9814-e6ccb5ede00b.png">
e.

**Comment by insanum** [comment]
Ah yes. Only in edit mode. I see the same and will provide a fix.

**Comment by insanum** [comment]
fixed

**Comment by nwehrle** [comment]
Thank you, that was quick.
