### ISSUE TITLE
The table is not very clear, can you add a color scheme for the table?

### ISSUE THREAD

**Issue by lin0kin** [insanum/obsidian_nord#26]
like ITS theme , it's adding customer color scheme for table

thx

**Comment by insanum** [comment]
Well to me tables look ok. Could you provide a pull request with changes to tables that you'd like to see? Then we can decide if the changes are worthwhile and enhance the theme overall.

**Comment by lin0kin** [comment]
> Well to me tables look ok. Could you provide a pull request with changes to tables that you'd like to see? Then we can decide if the changes are worthwhile and enhance the theme overall.

Sorry to reply to you only now

This is the look of a css I'm using

<img width="689" alt="Snipaste_2021-12-18_21-10-35" src="https://user-images.githubusercontent.com/30078096/146642306-84155dae-b8f9-438d-9bd1-0c21858bee12.png">

This is a table style from another theme

<img width="572" alt="Snipaste_2021-12-18_21-09-57" src="https://user-images.githubusercontent.com/30078096/146642309-ec1dcced-1cf6-4699-bf26-37795c490867.png">

**Comment by vii33** [comment]
Hi,
I created a pull request for this: https://github.com/insanum/obsidian_nord/pull/36

I went for a bit more subtle colors, though. Reason being that tables are normally embedded inside text areas and therefore shoud not stand out too much (also the headlines are already quite colorful in this theme).

**Original | New**
![theme-dark](https://user-images.githubusercontent.com/1887246/160261680-0a3d4186-ecf4-4762-900c-46b5a15133b2.png)

**Comment by lin0kin** [comment]
> Hi, I created a pull request for this: #36
> 
> I went for a bit more subtle colors, though. Reason being that tables are normally embedded inside text areas and therefore shoud not stand out too much (also the headlines are already quite colorful in this theme).
> 
> **Original | New** ![theme-dark](https://user-images.githubusercontent.com/1887246/160261680-0a3d4186-ecf4-4762-900c-46b5a15133b2.png)

this looks awesome , bro
