### ISSUE TITLE
Highlighting covers text (Obsidian 0.7.1)

### ISSUE THREAD

**Issue by b3u** [insanum/obsidian_nord#3]
When I remove the following line :point_down:, the problem disappears.
https://github.com/insanum/obsidian_nord/blob/924ede03d140dda307f0d10327fc650f27ca8f67/obsidian.css#L382-L385

Does that line do anything important? If so, I have an idea to fix it. I can open a PR.

**GIF of bug**
![GIF of bug](https://user-images.githubusercontent.com/39805353/84395220-f546f380-abcb-11ea-9886-3290f6f9160a.gif)

**Comment by insanum** [comment]
Fixed! Thanks for letting me know. :-)

The z-index was there because of a prior issue I saw in vim mode when highlighting text. I've removed that and added a color for `--text-selection`. This shows correctly in the editor but for some reason doesn't change view mode.
