### ISSUE TITLE
Search highlight bug

### ISSUE THREAD

**Issue by aubreyz** [insanum/obsidian_nord#32]
Great theme thanks for creating

Related to https://github.com/insanum/obsidian_nord/issues/21 there remains a bug with highlighting of find results. 

Control-F Find and then F3 to go through search results in file. 

- Hits in plain text are highlighted just fine. 
- Hits within code blocks are also fine.
- Hits within `inline code like this` are virtually impossible to see  (there is an almost invisible fine line)

I using Dark Theme

**Comment by insanum** [comment]
Theme has been rewritten for Obsidian 0.16.
