### ISSUE TITLE
Heading font size inconsistencies since Obsidian 0.13.27

### ISSUE THREAD

**Issue by gkertai** [insanum/obsidian_nord#33]
Since Obsidian [v0.13.27](https://forum.obsidian.md/t/obsidian-release-v0-13-27-insider-build/33223) (insider build) switching between edit & reading modes changes the font size of headings significantly (like 3-fold). I found this to affect the [obisidian_nord](https://github.com/insanum/obsidian_nord) and [obisidian_gruvbox](https://github.com/insanum/obsidian_gruvbox) themes, like so:

![8fb8baac289e83feaa531c863403bf2c0b7fc901_2_690x160](https://user-images.githubusercontent.com/1874498/156161861-375727b6-ed4b-4fba-baa9-4550b45594f0.png)

According to [Lilcat](https://forum.obsidian.md/u/Licat) (Obisidian developer):

> Heading sizing has been re-done - we moved them from the inner text to the outer line container. I have tried adding some CSS overrides to avoid old themes from screwing it up, but some themes set them differently (or probably with a !important) which overrides our overrides. They can now be configured with `--h1`, etc which should make it a lot easier to style.

For further details see discussion at [this Obsidian bug report](https://forum.obsidian.md/t/huge-heading-font-sizes-in-0-13-27/33233).

**Comment by swehba** [comment]
I can confirm that this is a problem with the Obsidian Nord theme.

**Comment by jvidal-sysadmin** [comment]
+1

**Comment by mattcorr** [comment]
+1

I have _sort of_ tried to fix this with CSS overrides, but there is a massive difference between edit and reading modes...

**Comment by jendahorak** [comment]
+ 1

**Comment by insanum** [comment]
fixed

**Comment by mattcorr** [comment]
Awesome. Much better now. Thanks!
