### ISSUE TITLE
[Improvement] Same tag highlight in edit and reading view

### ISSUE THREAD

**Issue by vii33** [insanum/obsidian_nord#35]
Hi, I love your theme. Thanks a lot for creating it! 🤩

I have one question, though: Is there a reason why tags aren't visualized the same in the edit and reading view?

**Example:**
![grafik](https://user-images.githubusercontent.com/1887246/159100276-292d20d0-9fa1-4e85-93cd-cd773ec81ee0.png)
*Left: Edit view,  Right: Reading view*

I really like the "taggish" styling in the reading view so I updated the CSS in the edit view -> Same look:
![grafik](https://user-images.githubusercontent.com/1887246/159100351-ca3d2a08-858e-4666-a74d-ef5e1de37e7e.png)

-------------

Code:
```
/* ----------------------------------------------------------------------------------- */
/* STYLING OF TAGS */

span.cm-hashtag {
  color: var(--text-tag) !important;
  background-color: var(--background-secondary-alt);
  text-decoration: none !important;
  padding: 2px 0px 2px 0px;
}

span.cm-formatting-hashtag {
  padding: 3px 0px 2px 4px;
  border-radius: 4px 0px 0px 4px;  /* left radiuses */
}

span.cm-hashtag-end {
    padding: 2px 4px 2px 0px;
    border-radius: 0px 4px 4px 0px; /* right radiuses */
}

/* ----------------------------------------------------------------------------------- */
/*  Special styling for certain tag words (optional). Suffix the tag name, e.g. "todo" */

span.cm-tag-todo {
  color: #080808 !important;
  background: #d6ae5e; 
}
```
**Remarks for others interested**:
- Tags constists out of several segments, so padding has to be done in multiple elements
- Due to multiple segments border radiuses have to be applied only in start and end element
- Special tags can be styled quite easily with own css classes (here the #todo example)
- The hashtag is somehow rendered 1 pixel too low -> Hashtag color box has an offset (see image below). Solution: Either use a mathematically correct top-padding distance or use a perfect screen-padding. In above example the 3px in the formatting-hashtag for screen-perfect (instead of 2px like other top-paddings).

Offset bug:
![grafik](https://user-images.githubusercontent.com/1887246/159100664-1920d071-271d-46ed-a5b0-a54ad9c22ecd.png)

**Comment by insanum** [comment]
This was a good idea and I've implemented it. :-)
