### ISSUE TITLE
Serif font in reading mode since Obsidian v0.14.7

### ISSUE THREAD

**Issue by nununo** [insanum/obsidian_nord#38]
Hello,

Today, after upgrading to v0.14.7, I started getting a Serif font in reading mode. Having mentioned it in Obsidian Discord, Licat managed to replicate it. And said this:

> yeah it's an issue with the theme
> we moved the default stack

> it seems that the author is specifying the font information on :root instead of body
> and it's also using the outdated font variables

Please find the Discord discussion [here](https://discord.com/channels/686053708261228577/716028884885307432/968545402095796285).

I hope this helps you solve it.

Thanks!

**Comment by insanum** [comment]
fixed
