### ISSUE TITLE
Formatting tag same in preview/editor hides vim mode cursor

### ISSUE THREAD

**Issue by jeloi** [insanum/obsidian_nord#39]
With the latest update, my normal mode vim cursor disappears when selecting a tag:

Ex: Cursor on text outside of a tag
![image](https://user-images.githubusercontent.com/1616454/171087423-301962d8-349c-4f52-97c0-1504c220bb68.png)

Ex: Cursor on text inside of a tag:
![image](https://user-images.githubusercontent.com/1616454/171087477-6d9a61ce-6639-4af9-b96e-4bf16a66067c.png)

I am not use "Live Preview" mode, e.g I'm using the legacy editor (because Live Preview has other issues with Vim Mode)

**Comment by insanum** [comment]
Theme has been rewritten for Obsidian 0.16.
