### ISSUE TITLE
Issue with styling of tags with underscore

### ISSUE THREAD

**Issue by Medenor** [insanum/obsidian_nord#40]
Hello,

I have an issue with tags containing an underscore : when in editing mode, the tag's highlight isn't properly done. When in view mode, it's OK. See below (editing mode on left panel ; view mode on right panel) : 
![image](https://user-images.githubusercontent.com/60567543/175789853-0482f348-bb7a-4384-9c86-492baec0a387.png)

Removing the underscore solves the issue.

Thanks for this theme, I love it :)

**Comment by insanum** [comment]
Theme has been rewritten for Obsidian 0.16.
