### ISSUE TITLE
Some elements are not coloured like the preview screenshot of the theme

### ISSUE THREAD

**Issue by th4umiel** [insanum/obsidian_nord#42]
The italic and bold both are of the same color as the regular text and the highlight, for example, is of a different shade of light blue compared to the presented screenshot. 
Honestly I don't know if I'm doing something wrong, but I didn't have the same problem with other themes :( 

<img width="1440" alt="Schermata 2022-09-21 alle 22 34 29" src="https://user-images.githubusercontent.com/17257735/191605296-cb6c88a6-9ca6-4e22-8153-03ec9fd373b4.png">

**Comment by insanum** [comment]
You're not doing anything wrong. :-)

This is just the way the theme was originally coded. You could create a CSS snippet to override the bold/italic text color.

Note that for Obsidian 0.16+ this theme has been completely rewritten and I did add a color change to bold/italic text. Just hang on until you get access to the new version of Obsidian.
