### ISSUE TITLE
The checkboxes do not scale with the font size

### ISSUE THREAD

**Issue by Smeagol2069** [insanum/obsidian_nord#43]
When I set my Vault's font to the lowest font size, the boxes are too big in comparison to the text. Similarly when the font is large the boxes are small. 

Thank you for the theme, I would greatly appreciate if the boxes were scaled with the font size.

**Comment by insanum** [comment]
That is not the case for me. Preview or Edit mode the boxes scale.
![Screen Shot 2022-10-14 at 9 54 28 AM](https://user-images.githubusercontent.com/515747/195900905-5e045b61-d618-4f5e-a968-f8ead4595277.png)
![Screen Shot 2022-10-14 at 9 54 36 AM](https://user-images.githubusercontent.com/515747/195900919-c775ecfc-26a5-4d11-b4f0-8345dd884254.png)

**Comment by Smeagol2069** [comment]
Sorry, I forgot to specify that this occurs on mobile.

![Screenshot_20221014_130738.jpg](https://user-images.githubusercontent.com/78649849/195903526-056056f6-fdf1-4f70-a653-9c8b069b0546.jpg)![Screenshot_20221014_130759.jpg](https://user-images.githubusercontent.com/78649849/195903538-1eccfb5e-3c8e-4d04-90f9-28f925e22c22.jpg)

**Comment by insanum** [comment]
Closing this. Same problem occurs with the default theme. Please file this issue in the Obsidian forums.
