### ISSUE TITLE
After updating to v1.0 inline code `code` no longer highlighted

### ISSUE THREAD

**Issue by nicholas-owen** [insanum/obsidian_nord#45]
After updating Obsidian to v1.0 and updating this them, the inline code `code` highlighting as well as  ''' CODE '''  no longer appears ice blue (in dark theme), but remains white. If this is intentional, I would be grateful if you could let me know which css setting to alter to return it to previous functionality. Thanks!

**Comment by insanum** [comment]
Not intentional. Fixed in next version.
