### ISSUE TITLE
Colours and Callouts in 1.0

### ISSUE THREAD

**Issue by Halfsunk** [insanum/obsidian_nord#46]
![Screenshot 2022-10-15 at 12 49 32 am](https://user-images.githubusercontent.com/100328079/195863289-0b58ea92-2f0a-4d0e-a9a5-a98f5cb6c02d.png)

There seems to be an issue with the colours of multiple things, see yellow for italics, and orange for links in the screenshot.

Additionally, the new formatting for callouts looks radically different to the point where I'm not sure its intended.
<img width="553" alt="Screenshot 2022-10-13 at 10 49 19 pm" src="https://user-images.githubusercontent.com/100328079/195863959-04271c27-426c-4773-bb38-62bc5cde5d70.png">
OLD

![Screenshot 2022-10-15 at 12 52 01 am](https://user-images.githubusercontent.com/100328079/195863947-2c8ab78b-cae0-40a3-8b04-6dedb63749de.png)
NEW

**Comment by insanum** [comment]
The yellow color for italics and bold is new and I added it with the v1.x of Obsidian. The previous white color did not offer enough contrast. You can easily revert this with a CSS snippet.

Regarding callouts, the theme does not modify those whatsoever. What you're seeing is the new default theming in Obsidian.

If you think there is a bug in any theme, make sure to always compare what you see to the default theme. Sometimes it's wackiness in upstream Obsidian. :-)
