### ISSUE TITLE
text highlighting on code

### ISSUE THREAD

**Issue by goodsignal** [insanum/obsidian_nord#5]
This is such a great theme! And I want to use it. That's why I'm bugging you :) 
Would you please check your highlighting fix on Editor window code block sections? All highlighting appears to be obscured behind the code background color.
 
![image](https://user-images.githubusercontent.com/10997567/84747898-19e30700-afe2-11ea-9341-49ec46e98046.png)

**Comment by insanum** [comment]
Thanks for the report. Fixed! :-)
