### ISSUE TITLE
[[Link]] color being same as ## H2 is confusing

### ISSUE THREAD

**Issue by Ali-C-Ila** [insanum/obsidian_nord#50]
## Usecase and Problem
In Obsidian, ``## Heading lv 2`` is used very often, and ``[[links]]`` are also used very often, and these two having the same orange color makes it a little counter-intuitive to read.

And for my case, things are even worse because I sometimes compound links AND headings, which looks like ``## [[Heading]]``. 
![image](https://user-images.githubusercontent.com/56729449/195974424-dd2b233c-5c15-40cb-a1e2-68f6f722bbba.png)
(Probably not the best habit I admit, but convenient when a note is starting to grow too long.)

So now I have no way to tell if a H2 is also a link or not before I click it. Which is pretty annoying. (For example in the screen shot above, "fossa ovalis" is a link, which I will likely fail to notice the next time I want to review this note.)

(BTW, I also think bold text, page title and H3 having the same color is a little confusing.)

## Suggestion
1. Use a more special color for Links (possibly the blue ones of Nord color, depending on your aethetics.)
2. Add option to customize colors.

(I must say, the Nord theme is masterpiece apart from these small nuances, austere, calming, inspiring..... I just don't know how to describe it.)

**Comment by insanum** [comment]
This was fixed yesterday. The link color is no longer used as one of the header colors so now there is contrast when a link is present in a header. Let me know what you think.

**Comment by Ali-C-Ila** [comment]
I'm absolutely in love with it! Thanks for the timely update!
