### ISSUE TITLE
Is it possible to have a dedicated "Nord" section in "Style settings?

### ISSUE THREAD

**Issue by feedhopper** [insanum/obsidian_nord#51]
I love this theme and use it a lot.

It would be great to have more ways of customizing details via the "Style settings" plugin, like a lot of the other themes.

Is there a chance to implement it?

Personally, I would like to see ways to alter the layout of notes as well as UI / interface options

THANK YOU FOR YOUR HARD WORK!!!

**Comment by insanum** [comment]
Well... my goal of this theme (and gruvbox) is to keep it simple and as close to the default style as much as possible. I've made some very minimal small tweaks but nothing that would require the style plugin.

I feel that CSS snippets are the way to go for what you're suggesting. If you're getting crazy with the mods then maybe try another theme that offers support for the style plugin and also supports a nord coloscheme. Pretty sure there are a couple that do this.

Nonetheless... I'm open to any pull requests. :-)
