### ISSUE TITLE
Cursor misaligned with numbered lists and body tags

### ISSUE THREAD

**Issue by grantx2016** [insanum/obsidian_nord#52]
Hi,

I have noticed that the cursor is misaligned when positioned at start of the text string for numbered lists, or at the start of body tags, as shown on the attached. I would expect there to be no gap between the cursor and the first character, as is normally the case.

Thanks for a great theme!

![tinywow_Screen Recording 2022-11-11 at 9 23 57 am_8055805](https://user-images.githubusercontent.com/19563571/201459028-90ee507c-2e16-4ef9-847e-a8377bfd02b7.gif)
![tinywow_Screen Recording 2022-11-11 at 9 40 41 am_8055741](https://user-images.githubusercontent.com/19563571/201459035-ef0835a7-fc27-4489-b4d6-6e94cafb98e0.gif)

**Comment by insanum** [comment]
I don't see these symptoms on my install. Can you try with the default theme (or others)?

**Comment by grantx2016** [comment]
I just tested with the default them:

- Numbered list: The issue does not exist.
- Tag: The same behaviour is observed as with the Nord theme, ie. when the cursor is positioned before the `#` it is positioned at the start of the pill shaped background colour.

Refer attached.
![tinywow_Screen Recording 2022-11-19 at 10 28 46 am_8393816](https://user-images.githubusercontent.com/19563571/202819999-5333b420-7084-4fc0-bc86-04930c3854ca.gif)

**Comment by ssimms** [comment]
I'm seeing the same issue with bulleted and numbered lists (Obsidian 1.1.6, Obsidian Nord 0.1.7).  Disabling the `.cm-formatting-list` rule fixes the problem.

**Comment by grantx2016** [comment]
> Disabling the `.cm-formatting-list` rule fixes the problem.

I couldn't get this to work. Can you please share the css to do this?

**Comment by mpaluta** [comment]
I have the same issue with bulleted lists and it's a minor annoyance. I keep hitting delete thinking I am deleting a space but it deletes characters.

**Comment by insanum** [comment]
This annoyed me as well. Fixed!
