### ISSUE TITLE
May we have colors for comment syntax?

### ISSUE THREAD

**Issue by yett1873** [insanum/obsidian_nord#54]
The theme doesn’t seem to be rendering texts wrapped in <! --- text ---> and %% text %%. May we have this feature? Thanks in advance!

**Comment by insanum** [comment]
Those resort to hidden content when rendered in HTML. You'll see those lines in the editor but not in preview.
When I test this, every theme I tried does the same thing by hiding the text in preview. Even the default theme.

I suggest asking on the Obsidian forums for this feature.
