### ISSUE TITLE
Current highlighted line confusing to read around codeblocks

### ISSUE THREAD

**Issue by shadyabhi** [insanum/obsidian_nord#55]
First of all, thanks for a great theme. 

The current highlighted line is hard to read, kind of like, my cursor gets lost when working with code-blocks. 

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/631797/205456213-8e5cf352-5d58-4b4c-b6d5-7aedf5686824.png">

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/631797/205456260-48f8a7ea-7bbc-490c-ba7c-34b33529b4ed.png">

**Comment by insanum** [comment]
Yeah, this annoyed me as well. After lots of trials I settled on changing the cursor line to a faded red. Looks good and hopefully doesn't annoy people. :-)
