### ISSUE TITLE
Heading colors are off 

### ISSUE THREAD

**Issue by 0xFlo** [insanum/obsidian_nord#56]
Can you help me get the heading colors fixed again?

See the screenshot it is different from what it used to be
<img width="835" alt="Screenshot 2022-12-10 at 10 08 07" src="https://user-images.githubusercontent.com/57475226/206849379-3b446b51-0d69-48be-ae1c-dd3d1e97aade.png">

**Comment by insanum** [comment]
Not sure what you're asking. In the image you show, that's the current colors used by Nord. I know I changed the headings with the rewrite in Obsidian 1.0 CSS engine changes as there were colors repeating and it didn't look good. If you'd like to see different colors then override the headings with the --h#-color: <color> attributes in your custom CSS.
