### ISSUE TITLE
HTML <mark> tag does not work inside callout blocks

### ISSUE THREAD

**Issue by EstebanRiv** [insanum/obsidian_nord#58]
HTML <mark> tag does not work as expected inside callout blocks, it behaves as markdown highlight (==link this==).
- Screenshot was taken in "live preview" mode.
- In "reading mode" the behavior is consistent and html `<mark>` tags are rendered as markdown highlight both inside and outside callout blocks.
- Sample code provided.

```html
> [!error] HTML bg and fg are not displayed correctly in callouts
> <mark style="color: white; background: #24799a;">Blue</mark>, 
> <mark style="color: white; background: #780000;">red</mark>, 
> <mark style="color: white; background: #006812;">green</mark>

Same HTML code outside a callout
<mark style="color: white; background: #24799a;">Blue</mark>, 
<mark style="color: white; background: #780000;">red</mark>, 
<mark style="color: white; background: #006812;">green</mark>
```
![Nord_HtmlTagInCallout](https://user-images.githubusercontent.com/25851064/226205421-622b75f0-0675-4cd2-8018-0961f6f8c235.png)

**Comment by insanum** [comment]
Thanks for reporting this issue. Fixed!
