### ISSUE TITLE
highlight

### ISSUE THREAD

**Issue by visualcurrent** [insanum/obsidian_nord#6]
Thank you for the recent highlight fix!

Everything is workable. but I think the issue is still present on inline code. But, I can't tell if the current design is intentional or not. You can see a sliver of highlight on inline code because the highlight entity is slightly taller than the inline background. But it's mostly hidden behind.

Regards

**Comment by insanum** [comment]
Just looked into this and noticed that the behavior is the same in the default theme (i.e. disable the CSS plugin). We need to report this to the Obsidian devs on the forum or Discord.

**Comment by goodsignal** [comment]
I just mentioned it on the insider-build channel. Sorry I didn't notice that it was universal. It just seemed so related to my previous highlighting request :)

**Comment by insanum** [comment]
This is fixed in the latest versions of Obsidian.
