### ISSUE TITLE
Issue with internal link and preview 

### ISSUE THREAD

**Issue by kazumas44** [insanum/obsidian_nord#61]
Maybe that's just me 
But when I put a internal link to another note, in the middle of a text. The link will not work and appear simply as text. 
This happen only in reading mod

**Comment by insanum** [comment]
I use `[[ ... ]]` internal links all the time without issue. Can you show an example? Also please confirm you don't see the same issue with the default theme.

**Comment by kazumas44** [comment]
I think i understood what created this bug
The theme isn't related with it, it might be the <br> i used before the text 
Had this issue with the default theme
