### ISSUE TITLE
Change header color

### ISSUE THREAD

**Issue by PavelNikov** [insanum/obsidian_nord#62]
I want to change the color of h1.

**Code in my css snippet**:
`body {
        --h1-color: #8fbcbb;
}
`

**Expected result**: h1 header turning green instead of yellow.

**Actual result**: h1 header stays yellow.

Why?

(Sorry if I missed something obvious; Thanks a ton for putting in the work to port this awesome theme to Obsidian!)

**Comment by insanum** [comment]
Use this instead. This should work with any theme.

```
.theme-dark { --h1-color: #8fbcbb; }
```
