### ISSUE TITLE
suggest add an outline view function(looking)

### ISSUE THREAD

**Issue by OrdinaryYZH** [insanum/obsidian_nord#9]
Thank you for your beautiful theme, and I think add  an outline view like roam research is more useful and valuable.

Like this:

![image](https://user-images.githubusercontent.com/10287222/99216267-3a70f080-2810-11eb-8108-cc7b983b6801.png)

And I found a theme realized this function,https://github.com/nickmilo/Cybertron

![image](https://user-images.githubusercontent.com/10287222/99216741-5fb22e80-2811-11eb-9090-8fbf6ce3038c.png)

But the nord theme is my favorite, so I hope the bsidian_nord theme can add this function :)

**Comment by OrdinaryYZH** [comment]
I found a post, and resolve it.

https://forum.obsidian.md/t/meta-post-common-css-hacks/1978/229

**Comment by sanpedrodeatacama** [comment]
I also wanted to say thanks for the Nord theme, it's such a pleasure to use. And I second @OrdinaryYZH's request for the bullet point lines if you agree. I'd also submit the request to make the highlight color something more visible. I have a lot of difficulty locating a searched term with the current light blue color. These are minor desires in an excellent theme, thanks again for what you've made.

**Comment by insanum** [comment]
Glad you like Nord. :-)
Using Obsidian CSS snippets is definitely the right way to enable this. This post has the snippet for the roam-like lists:
https://forum.obsidian.md/t/meta-post-common-css-hacks/1978/246?u=insanum
